---
title: "Statistics"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 1 Value weighted stocks
## 1.1 BRIC
```{r}
# factors
factors_BRIC

# benchmark
full_BRIC_Benchmark

# 3 Factor ----

## growth + lowVol + Momentum
full_BRIC_ValueWeight

# 2 Factor ----

## growth + lowVol
growthLowVol_BRIC_ValueWeight
## growth + Momentum
growthMom_BRIC_ValueWeight
## lowVol + Momentum
lowVolMom_BRIC_ValueWeight

# 1 Factor ----

## growth
growth_BRIC_ValueWeight
## lowVol
lowVol_BRIC_ValueWeight
## Momentum
Mom_BRIC_ValueWeight


#lowVol_BRIC_ValueWeight <- c(strategy.retBricT,strategy.retExBricT,strategy.sdBricT,strategy.srBricT,strategy.mdBricT,strategy.teBricT,strategy.irBricT, strategy.avgNumberOfStocks, strategy.topTenBricT, strategy.turnover, nrow(strategy))
# merge data sheets

differentStrategies.BRIC <- rbind(full_BRIC_Benchmark,full_BRIC_ValueWeight,full_valueInsteadofGrowth_BRIC_ValueWeight,growthLowVol_BRIC_ValueWeight,growthMom_BRIC_ValueWeight,lowVolMom_BRIC_ValueWeight,growth_BRIC_ValueWeight,lowVol_BRIC_ValueWeight,Mom_BRIC_ValueWeight)
differentStrategies.BRIC <- as.data.frame(differentStrategies.BRIC)

colnames_Strategy_Statics<- c("Return","ExcessReturn","Volatility","SharpeRatio","MaxDrawdown","TrackingError","InformationRatio","#NoOfStocks","PortfolioConcentration","Turnover","NumberOfRows")
colnames(differentStrategies.BRIC) <- colnames_Strategy_Statics

# export
save(factors_BRIC,file = "factors_BRIC.RData")
save(differentStrategies.BRIC,file = "differentStrategies_BRIC.RData")


```
## 1.2 Countries
```{r}
# 1.2.1 China ----

# factors
factors_CHN

# benchmark
full_CHN_Benchmark

# 3 Factor ----

## growth + lowVol + Momentum
full_CHN_ValueWeight

# 2 Factor ----

## growth + lowVol
growthLowVol_CHN_ValueWeight
## growth + Momentum
growthMom_CHN_ValueWeight
## lowVol + Momentum
lowVolMom_CHN_ValueWeight

# 1 Factor ----

## growth
growth_CHN_ValueWeight
## lowVol
lowVol_CHN_ValueWeight
## Momentum
Mom_CHN_ValueWeight

# merge data sheets

differentStrategies.CHN <- rbind(full_CHN_Benchmark,full_CHN_ValueWeight,growthLowVol_CHN_ValueWeight,growthMom_CHN_ValueWeight,lowVolMom_CHN_ValueWeight,growth_CHN_ValueWeight,lowVol_CHN_ValueWeight,Mom_CHN_ValueWeight)
differentStrategies.CHN <- as.data.frame(differentStrategies.CHN)

colnames_Strategy_Statics<- c("Return","ExcessReturn","Volatility","SharpeRatio","MaxDrawdown","TrackingError","InformationRatio","#NoOfStocks","PortfolioConcentration","Turnover","NumberOfRows")
colnames(differentStrategies.CHN) <- colnames_Strategy_Statics

# export
save(factors_CHN,file = "factors_CHN.RData")
save(differentStrategies.CHN,file = "differentStrategies_CHN.RData")

# 1.2.2 Russia ----

# factors
factors_RUS

# benchmark
full_RUS_Benchmark

# 3 Factor ----

## growth + lowVol + Momentum
full_RUS_ValueWeight

# 2 Factor ----

## growth + lowVol
growthLowVol_RUS_ValueWeight
## growth + Momentum
growthMom_RUS_ValueWeight
## lowVol + Momentum
lowVolMom_RUS_ValueWeight

# 1 Factor ----

## growth
growth_RUS_ValueWeight
## lowVol
lowVol_RUS_ValueWeight
## Momentum
Mom_RUS_ValueWeight

# merge data sheets

differentStrategies.RUS <- rbind(full_RUS_Benchmark,full_RUS_ValueWeight,growthLowVol_RUS_ValueWeight,growthMom_RUS_ValueWeight,lowVolMom_RUS_ValueWeight,growth_RUS_ValueWeight,lowVol_RUS_ValueWeight,Mom_RUS_ValueWeight)
differentStrategies.RUS <- as.data.frame(differentStrategies.RUS)

colnames_Strategy_Statics<- c("Return","ExcessReturn","Volatility","SharpeRatio","MaxDrawdown","TrackingError","InformationRatio","#NoOfStocks","PortfolioConcentration","Turnover","NumberOfRows")
colnames(differentStrategies.RUS) <- colnames_Strategy_Statics

# export
save(factors_RUS,file = "factors_RUS.RData")
save(differentStrategies.RUS,file = "differentStrategies_RUS.RData")

# 1.2.3 India ----

# factors
factors_IND

# benchmark
full_IND_Benchmark

# 3 Factor ----

## growth + lowVol + Momentum
full_IND_ValueWeight

# 2 Factor ----

## growth + lowVol
growthLowVol_IND_ValueWeight
## growth + Momentum
growthMom_IND_ValueWeight
## lowVol + Momentum
lowVolMom_IND_ValueWeight

# 1 Factor ----

## growth
growth_IND_ValueWeight
## lowVol
lowVol_IND_ValueWeight
## Momentum
Mom_IND_ValueWeight

# merge data sheets

differentStrategies.IND <- rbind(full_IND_Benchmark,full_IND_ValueWeight,growthLowVol_IND_ValueWeight,growthMom_IND_ValueWeight,lowVolMom_IND_ValueWeight,growth_IND_ValueWeight,lowVol_IND_ValueWeight,Mom_IND_ValueWeight)
differentStrategies.IND <- as.data.frame(differentStrategies.IND)

colnames_Strategy_Statics<- c("Return","ExcessReturn","Volatility","SharpeRatio","MaxDrawdown","TrackingError","InformationRatio","#NoOfStocks","PortfolioConcentration","Turnover","NumberOfRows")
colnames(differentStrategies.IND) <- colnames_Strategy_Statics

# export
save(factors_IND,file = "factors_IND.RData")
save(differentStrategies.IND,file = "differentStrategies_IND.RData")

# 1.2.4 Brazil ----

# factors
factors_BRA

# benchmark
full_BRA_Benchmark

# 3 Factor ----

## growth + lowVol + Momentum
full_BRA_ValueWeight

# 2 Factor ----

## growth + lowVol
growthLowVol_BRA_ValueWeight
## growth + Momentum
growthMom_BRA_ValueWeight
## lowVol + Momentum
lowVolMom_BRA_ValueWeight

# 1 Factor ----

## growth
growth_BRA_ValueWeight
## lowVol
lowVol_BRA_ValueWeight
## Momentum
Mom_BRA_ValueWeight

# merge data sheets

differentStrategies.BRA <- rbind(full_BRA_Benchmark,full_BRA_ValueWeight,growthLowVol_BRA_ValueWeight,growthMom_BRA_ValueWeight,lowVolMom_BRA_ValueWeight,growth_BRA_ValueWeight,lowVol_BRA_ValueWeight,Mom_BRA_ValueWeight)
differentStrategies.BRA <- as.data.frame(differentStrategies.BRA)

colnames_Strategy_Statics<- c("Return","ExcessReturn","Volatility","SharpeRatio","MaxDrawdown","TrackingError","InformationRatio","#NoOfStocks","PortfolioConcentration","Turnover","NumberOfRows")
colnames(differentStrategies.BRA) <- colnames_Strategy_Statics

# export
save(factors_BRA,file = "factors_BRA.RData")
save(differentStrategies.BRA,file = "differentStrategies_BRA.RData")

```

# Megaview
```{r}
differentStrategies.BRIC$Region <- "BRIC"
differentStrategies.CHN$Region <- "CHN"
differentStrategies.RUS$Region <- "RUS"
differentStrategies.IND$Region <- "IND"
differentStrategies.BRA$Region <- "BRA"
differentStrategies.all <- rbind(differentStrategies.BRIC,differentStrategies.CHN,differentStrategies.RUS,differentStrategies.IND,differentStrategies.BRA)
save(differentStrategies.all,file = "differentStrategies_all.RDATA")
```


